// Fill out your copyright notice in the Description page of Project Settings.


#include "BlueprintSupport/K2Node_CallGlobalLuaFunction.h"

#include "EdGraphSchema_K2.h"
#include "BlueprintSupport/UnrealLuaUtility.h"


namespace UnrealLuaScriptUtil
{
	const FName UFunctionFuncNameParamPropertyName = "funcName";
	const FName UFunctionNumArgsPropertyName = "numArguments";
	const FName UFunctionNumResultsPropertyName = "numResults";
}

UK2Node_CallGlobalLuaFunction::UK2Node_CallGlobalLuaFunction()
{
	FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UUnrealLuaUtility, CallGlobalLuaFunction), UUnrealLuaUtility::StaticClass());
}

void UK2Node_CallGlobalLuaFunction::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();
    
	// Hide the argument name pins
	// Note: Have to do this manually as the "HidePin" meta-data only lets you hide a single pin :(
	UEdGraphPin* PythonInputsPin = FindPinChecked(UnrealLuaScriptUtil::UFunctionNumArgsPropertyName, EGPD_Input);
	PythonInputsPin->bHidden = true;
	PythonInputsPin->DefaultValue = FString::FromInt(this->InputPinNames.Num());
	PythonInputsPin->AutogeneratedDefaultValue = FString::FromInt(this->InputPinNames.Num());
	UEdGraphPin* PythonOutputsPin = FindPinChecked(UnrealLuaScriptUtil::UFunctionNumResultsPropertyName, EGPD_Input);
	PythonOutputsPin->bHidden = true;
	PythonOutputsPin->DefaultValue = FString::FromInt(this->OutputPinNames.Num());;
	PythonOutputsPin->AutogeneratedDefaultValue = FString::FromInt(this->OutputPinNames.Num());
    	
	UEdGraphPin* PythonScriptPin = FindPinChecked(UnrealLuaScriptUtil::UFunctionFuncNameParamPropertyName, EGPD_Input);
	PythonScriptPin->AutogeneratedDefaultValue = TEXT("");
	PythonScriptPin->DefaultValue = PythonScriptPin->AutogeneratedDefaultValue;
    
	// Add user-defined pins
	auto AddUserDefinedPins = [this](TArray<FName>& InPinNames, EEdGraphPinDirection InPinDirection)
	{
		int32 index = 1;
		FString prefix = InPinDirection == EGPD_Input ? "Input" : "Output";
		for (FName& PinName : InPinNames)
		{
			FName usedPinName = PinName;
			if (PinName == NAME_None)
			{
				FString generatedPinName = prefix;
				generatedPinName.AppendInt(index);
				usedPinName = *generatedPinName;
				PinName = usedPinName;
			}
			UEdGraphPin* ArgPin = CreatePin(InPinDirection, UEdGraphSchema_K2::PC_Wildcard, usedPinName);
			ArgPin->PinFriendlyName = FText::AsCultureInvariant(ArgPin->GetName());
			index++;
		}
	};
	AddUserDefinedPins(InputPinNames, EGPD_Input);
	AddUserDefinedPins(OutputPinNames, EGPD_Output);;
}
