// Fill out your copyright notice in the Description page of Project Settings.


#include "BlueprintSupport/K2Node_BroadcastLuaDelegateOnObject.h"

#include "EdGraphSchema_K2.h"
#include "BlueprintSupport/UnrealLuaUtility.h"


namespace UnrealLuaScriptUtil
{
	const FName UFunctionSelfCallPropertyName = "target";
	const FName UFunctionNumArgsPropertyName = "numArguments";
}

UK2Node_BroadcastLuaDelegateOnObject::UK2Node_BroadcastLuaDelegateOnObject()
{
	FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UUnrealLuaUtility, BroadcastLuaDelegateInObject), UUnrealLuaUtility::StaticClass());
}

void UK2Node_BroadcastLuaDelegateOnObject::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();
	
	// Hide the argument num pin
	// Note: Have to do this manually as the "HidePin" meta-data only lets you hide a single pin :(
	UEdGraphPin* numArgsPin = FindPinChecked(UnrealLuaScriptUtil::UFunctionNumArgsPropertyName, EGPD_Input);
	numArgsPin->bHidden = true;
	numArgsPin->DefaultValue = FString::FromInt(this->InputPinNames.Num());
	numArgsPin->AutogeneratedDefaultValue = FString::FromInt(this->InputPinNames.Num());

	// Add user-defined pins
	auto AddUserDefinedPins = [this](TArray<FName>& InPinNames, EEdGraphPinDirection InPinDirection)
	{
		int32 index = 1;
		FString prefix = InPinDirection == EGPD_Input ? "Input" : "Output";
		for (FName& PinName : InPinNames)
		{
			FName usedPinName = PinName;
			if (PinName == NAME_None)
			{
				FString generatedPinName = prefix;
				generatedPinName.AppendInt(index);
				usedPinName = *generatedPinName;
				PinName = usedPinName;
			}
			UEdGraphPin* ArgPin = CreatePin(InPinDirection, UEdGraphSchema_K2::PC_Wildcard, usedPinName);
			ArgPin->PinFriendlyName = FText::AsCultureInvariant(ArgPin->GetName());
			index++;
		}
	};
	AddUserDefinedPins(InputPinNames, EGPD_Input);
}
