// Fill out your copyright notice in the Description page of Project Settings.


#include "BlueprintSupport/K2Node_CallLuaFunctionOnTable.h"

#include "EdGraphSchema_K2.h"
#include "BlueprintSupport/UnrealLuaUtility.h"


namespace UnrealLuaScriptUtil
{
	const FName UFunctionNumArgsPropertyName = "numArguments";
	const FName UFunctionNumResultsPropertyName = "numResults";
	const FName UFunctionSelfCallPropertyName = "selfCall";
}

UK2Node_CallLuaFunctionOnTable::UK2Node_CallLuaFunctionOnTable()
{
	FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UUnrealLuaUtility, CallLuaFunctionOnTable), UUnrealLuaUtility::StaticClass());
}

void UK2Node_CallLuaFunctionOnTable::AllocateDefaultPins()
{
		Super::AllocateDefaultPins();
    
    	// Hide the argument name pins
    	// Note: Have to do this manually as the "HidePin" meta-data only lets you hide a single pin :(
    	UEdGraphPin* PythonInputsPin = FindPinChecked(UnrealLuaScriptUtil::UFunctionNumArgsPropertyName, EGPD_Input);
    	PythonInputsPin->bHidden = true;
    	PythonInputsPin->DefaultValue = FString::FromInt(this->InputPinNames.Num());
    	PythonInputsPin->AutogeneratedDefaultValue = FString::FromInt(this->InputPinNames.Num());
    	UEdGraphPin* PythonOutputsPin = FindPinChecked(UnrealLuaScriptUtil::UFunctionNumResultsPropertyName, EGPD_Input);
    	PythonOutputsPin->bHidden = true;
    	PythonOutputsPin->DefaultValue = FString::FromInt(this->OutputPinNames.Num());;
    	PythonOutputsPin->AutogeneratedDefaultValue = FString::FromInt(this->OutputPinNames.Num());
    	
    	UEdGraphPin* useTargetAsSelf = FindPinChecked(UnrealLuaScriptUtil::UFunctionSelfCallPropertyName, EGPD_Input);
    	useTargetAsSelf->DefaultValue = "true";
    
    	// Add user-defined pins
    	auto AddUserDefinedPins = [this](TArray<FName>& InPinNames, EEdGraphPinDirection InPinDirection)
    	{
    		int32 index = 1;
    		FString prefix = InPinDirection == EGPD_Input ? "Input" : "Output";
    		for (FName& PinName : InPinNames)
    		{
    			FName usedPinName = PinName;
    			if (PinName == NAME_None)
    			{
    				FString generatedPinName = prefix;
    				generatedPinName.AppendInt(index);
    				usedPinName = *generatedPinName;
    				PinName = usedPinName;
    			}
    			UEdGraphPin* ArgPin = CreatePin(InPinDirection, UEdGraphSchema_K2::PC_Wildcard, usedPinName);
    			ArgPin->PinFriendlyName = FText::AsCultureInvariant(ArgPin->GetName());
    			index++;
    		}
    	};
    	AddUserDefinedPins(InputPinNames, EGPD_Input);
    	AddUserDefinedPins(OutputPinNames, EGPD_Output);
}
