// Fill out your copyright notice in the Description page of Project Settings.


#include "BlueprintSupport/K2Node_MakeLuaValue.h"

#include "EdGraphSchema_K2.h"
#include "BlueprintSupport/UnrealLuaUtility.h"


namespace UnrealLuaScriptUtil
{
	const FName NumItems = "numItems";
}

UK2Node_MakeLuaValue::UK2Node_MakeLuaValue()
{
	FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UUnrealLuaUtility, MakeLuaValue), UUnrealLuaUtility::StaticClass());
}


void UK2Node_MakeLuaValue::PostInitProperties()
{
	LUA_LOG_WARNING("UK2Node_MakeLuaValue::PostInitProperties")
	Super::PostInitProperties();
}

void UK2Node_MakeLuaValue::PostLoad()
{
	LUA_LOG_WARNING("UK2Node_MakeLuaValue::PostLoad")
	Super::PostLoad();
}

void UK2Node_MakeLuaValue::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();

	// Hide the argument name pins
	// Note: Have to do this manually as the "HidePin" meta-data only lets you hide a single pin :(
	UEdGraphPin* PythonOutputsPin = FindPinChecked(UnrealLuaScriptUtil::NumItems, EGPD_Input);
	PythonOutputsPin->bHidden = true;
	PythonOutputsPin->DefaultValue = FString::FromInt(this->InputPinNames.Num());
	PythonOutputsPin->AutogeneratedDefaultValue = FString::FromInt(this->InputPinNames.Num());
	
	this->ProcessAndSyncPinNames();
	
	verify(this->InputPinNames.Num() == this->OutputPinNames.Num());
	// Add user-defined pins
	for (int32 i = 0; i < this->InputPinNames.Num(); ++i)
	{
		FName inputPinName = this->InputPinNames[i];
		FName outputPinName = this->OutputPinNames[i];
		
		UEdGraphPin* ArgPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Wildcard, inputPinName);
		ArgPin->PinFriendlyName = FText::AsCultureInvariant(ArgPin->GetName());
		
		UEdGraphPin* OutPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, outputPinName);
		OutPin->PinType.PinSubCategoryObject = FLuaValue::StaticStruct();
		OutPin->PinFriendlyName = FText::AsCultureInvariant(OutPin->GetName());
	}
}

FEdGraphPinType UK2Node_MakeLuaValue::GetDefaultPinTypeForPin(UEdGraphPin* Pin)
{
	FEdGraphPinType newType;
	if (Pin->Direction == EGPD_Input)
	{
		newType.PinCategory =  UEdGraphSchema_K2::PC_Wildcard;
	}
	else
	{
		newType.PinCategory =  UEdGraphSchema_K2::PC_Struct;
		newType.PinSubCategoryObject = FLuaValue::StaticStruct();
	}
	return newType;
}
