// Fill out your copyright notice in the Description page of Project Settings.


#include "BlueprintSupport/K2Node_SetStaticClassDataValue.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "BlueprintSupport/UnrealLuaUtility.h"

#define LOCTEXT_NAMESPACE "UnrealLuaEditor"
namespace UnrealLuaScriptUtil
{
	const FName Target = "target";
	const FName PropertyName = "propertyName";
	const FName PropertyValue = "value";
}

UK2Node_SetStaticClassDataValue::UK2Node_SetStaticClassDataValue()
{
	FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UUnrealLuaUtility, SetStaticClassDataValue), UUnrealLuaUtility::StaticClass());
}

void CreatePinAndStringPinForProperty(UK2Node_SetStaticClassDataValue* node, FProperty* prop, FName inputPinName)
{
	if (prop)
	{
		if (FIntProperty* intProperty = CastField<FIntProperty>(prop))
		{
			UEdGraphPin* ArgPin = node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, inputPinName);
			ArgPin->PinFriendlyName = FText::AsCultureInvariant(ArgPin->GetName());
			
			UEdGraphPin* ArgNamePin = node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, *(inputPinName.ToString() + "_HiddenInput"));
			ArgNamePin->PinFriendlyName = FText::AsCultureInvariant(ArgPin->GetName() + "_HiddenInput");
			ArgNamePin->DefaultValue = inputPinName.ToString();
			ArgNamePin->AutogeneratedDefaultValue = inputPinName.ToString();
			ArgNamePin->bHidden = true;
			ArgNamePin->bNotConnectable = true;
			//ArgNamePin->bHidden = true;			
		}
	}
	else
	{
		LUA_LOG_WARNING("Prop %s not found", *node->StaticPropertyName)	
	}
}

void UK2Node_SetStaticClassDataValue::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();
		
	//this->ProcessAndSyncPinNames();
	// Add user-defined pins
	
	UEdGraphPin* targetPin = FindPinChecked(UnrealLuaScriptUtil::Target, EGPD_Input);
	UEdGraphPin* propertyNamePin = FindPinChecked(UnrealLuaScriptUtil::PropertyName, EGPD_Input);
	UEdGraphPin* propertyValuePin = nullptr;
	targetPin->bHidden = true;
	FString propertyNamePinValue = "";
	FString propertyValuePinDisplayName = "";
	//UClass* uclass = Cast<UClass>(targetPin->PinType.PinSubCategoryObject.Get());
	UClass* uclass = this->GetBlueprint()->GeneratedClass;
	if (uclass)
	{
		//}
		//if (uclass)
		//{
		UScriptStruct* staticDataStruct = uclass->GetSparseClassDataStruct();
	
		if (staticDataStruct)
		{
			
			void* staticData = uclass->GetOrCreateSparseClassData();
			if (this->StaticPropertyName.IsEmpty())
			{
				TFieldIterator<FProperty> it{staticDataStruct};
				if (it)
				{
					this->StaticPropertyName = *it->GetName();
				}
			}
			if (!this->StaticPropertyName.IsEmpty())
			{
				LUA_LOG("Setting static property node %s in class %s", *this->StaticPropertyName, *GetFullNameSafe(uclass))
				
				FName inputPinName = *this->StaticPropertyName;
		
				FProperty* staticProp = staticDataStruct->FindPropertyByName(inputPinName);
				if (staticProp)
				{
					if (FIntProperty* intProperty = CastField<FIntProperty>(staticProp))
					{
						propertyNamePinValue = staticProp->GetName();
						propertyValuePin = this->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, UnrealLuaScriptUtil::PropertyValue);
						propertyValuePinDisplayName = this->StaticPropertyName;
					}
					else if (FFloatProperty* floatProp = CastField<FFloatProperty>(staticProp))
					{
						propertyNamePinValue = staticProp->GetName();
						propertyValuePin = this->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Float, UnrealLuaScriptUtil::PropertyValue);
						propertyValuePinDisplayName = this->StaticPropertyName;
					}
					else if (FDoubleProperty* doubleProp = CastField<FDoubleProperty>(staticProp))
					{
						propertyNamePinValue = staticProp->GetName();
						propertyValuePin = this->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Double, UnrealLuaScriptUtil::PropertyValue);
						propertyValuePinDisplayName = this->StaticPropertyName;
					}
					else if (FStrProperty* strProp = CastField<FStrProperty>(staticProp))
					{
						propertyNamePinValue = staticProp->GetName();
						propertyValuePin = this->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_String, UnrealLuaScriptUtil::PropertyValue);
						propertyValuePinDisplayName = this->StaticPropertyName;
					}
					else
					{
						LUA_LOG_WARNING("Type of static property node %s in class %s not supported yet!", *this->StaticPropertyName, *GetFullNameSafe(uclass))
						propertyValuePinDisplayName = "[InvalidProperty]";
					}
				}
				else
				{
					LUA_LOG_WARNING("Static property not found on node %s in class %s!", *this->StaticPropertyName, *GetFullNameSafe(uclass))
					propertyValuePinDisplayName = "[InvalidProperty]";
				}
			}
			else
			{
				LUA_LOG_WARNING("Prop name is empty for class %s", *GetFullNameSafe(uclass));
				propertyValuePinDisplayName = "[InvalidProperty]";
			}
		}
		else
		{
			LUA_LOG_WARNING("No static data in class %s", *GetFullNameSafe(uclass))
			propertyValuePinDisplayName = "[InvalidProperty]";
		}
	}
	else
	{
		LUA_LOG_WARNING("No generated class")
		propertyValuePinDisplayName = "[InvalidProperty]";
	}
	
	if (propertyValuePin == nullptr)
	{
		propertyValuePin = this->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Wildcard, UnrealLuaScriptUtil::PropertyValue);
	}
	propertyValuePin->PinFriendlyName = FText::AsCultureInvariant(propertyValuePinDisplayName);
	
	propertyNamePin->DefaultValue = propertyNamePinValue;
	propertyNamePin->AutogeneratedDefaultValue = propertyNamePinValue;
	propertyNamePin->bNotConnectable = true;
	propertyNamePin->bHidden = !this->bShowHiddenPins;
	propertyNamePin->PinType.bIsConst = true;
}


bool UK2Node_SetStaticClassDataValue::CanPasteHere(const UEdGraph* TargetGraph) const
{
	bool bCanPaste = Super::CanPasteHere(TargetGraph);
	//if (bCanPaste)
	//{
	//	bCanPaste &= FBlueprintEditorUtils::IsEditorUtilityBlueprint(FBlueprintEditorUtils::FindBlueprintForGraphChecked(TargetGraph));
	//}
	return bCanPaste;
}

bool UK2Node_SetStaticClassDataValue::IsActionFilteredOut(const FBlueprintActionFilter& Filter)
{
	bool bIsFilteredOut = Super::IsActionFilteredOut(Filter);
	if (!bIsFilteredOut)
	{
		for (UEdGraph* TargetGraph : Filter.Context.Graphs)
		{
			bIsFilteredOut |= !CanPasteHere(TargetGraph);
		}
	}
	return bIsFilteredOut;
}

void UK2Node_SetStaticClassDataValue::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	UEdGraphPin* selfpin = this->FindPin(TEXT("target"), EGPD_Input);
	if (!selfpin || !selfpin->PinType.PinSubCategoryObject.IsValid())
	{
		MessageLog.Error(*FString("Pin is not valid or not a UObject pin."));
	}
	/*
	for (const FName& PinName : this->InputPinNames)
	{
		const FString PythonizedPinName = PinName.ToString();

		if (PinName == UEdGraphSchema_K2::PN_Execute ||
			PinName == UEdGraphSchema_K2::PN_Then ||
			PinName == UEdGraphSchema_K2::PN_ReturnValue
			)
		{
			MessageLog.Error(*FText::Format(LOCTEXT("InvalidPinName_RestrictedName", "Pin '{0}' ({1}) on @@ is using a restricted name."), FText::AsCultureInvariant(PinName.ToString()), FText::AsCultureInvariant(PythonizedPinName)).ToString(), this);
		}
		if (PythonizedPinName.Len() == 0)
		{
			MessageLog.Error(*LOCTEXT("InvalidPinName_EmptyName", "Empty pin name found on @@").ToString(), this);
		}
	}
	*/
}


void UK2Node_SetStaticClassDataValue::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	// actions get registered under specific object-keys; the idea is that 
	// actions might have to be updated (or deleted) if their object-key is  
	// mutated (or removed)... here we use the node's class (so if the node 
	// type disappears, then the action should go with it)
	UClass* ActionKey = GetClass();
	// to keep from needlessly instantiating a UBlueprintNodeSpawner, first   
	// check to make sure that the registrar is looking for actions of this type
	// (could be regenerating actions for a specific asset, and therefore the 
	// registrar would only accept actions corresponding to that asset)
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);

		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

void UK2Node_SetStaticClassDataValue::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);
	GetGraph()->NotifyNodeChanged(this);
}

void UK2Node_SetStaticClassDataValue::PinTypeChanged(UEdGraphPin* Pin)
{
	Super::PinTypeChanged(Pin);
	GetGraph()->NotifyNodeChanged(this);
}

void UK2Node_SetStaticClassDataValue::PostEditChangeProperty(struct FPropertyChangedEvent& propEditEvent)
{
	Super::PostEditChangeProperty(propEditEvent);
	FProperty* prop = propEditEvent.Property;
	if (prop->GetName() == GET_MEMBER_NAME_CHECKED(UK2Node_SetStaticClassDataValue, StaticPropertyName))
	{
		ReconstructNode();
	}
	else if (prop->GetName() == GET_MEMBER_NAME_CHECKED(UK2Node_SetStaticClassDataValue, bShowHiddenPins))
	{
		ReconstructNode();
	}
	GetGraph()->NotifyNodeChanged(this);
}

TArray<FString> UK2Node_SetStaticClassDataValue::GetPropertyNames() const
{
	TArray<FString> propNames{};
	UClass* uclass = this->GetBlueprint()->GeneratedClass;
	//UEdGraphPin* targetPin = FindPinChecked(UnrealLuaScriptUtil::Target, EGPD_Input);
	//UClass* uclass = Cast<UClass>(targetPin->PinType.PinSubCategoryObject.Get());
	if (uclass)
	{
		UScriptStruct* staticDataStruct = uclass->GetSparseClassDataStruct();
		if (staticDataStruct)
		{
			for (TFieldIterator<FProperty> It(staticDataStruct); It; ++It)
			{
				propNames.Emplace(It->GetName());
			}
		}
		else
		{
			LUA_LOG_WARNING("GetPropertyNames: No static data struct in uclass %s", *GetFullNameSafe(uclass))	
		}
	}
	else
	{
		LUA_LOG_WARNING("GetPropertyNames: No generated class")
	}
	
	return propNames;
}

#undef LOCTEXT_NAMESPACE